import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { ProductProvider } from "@/contexts/ProductContext";
import { ProductTypeProvider } from "@/contexts/ProductTypeContext";
import { CartContextProvider } from "@/contexts/CartContext";
import { LocationProvider } from "@/contexts/LocationContext";
import { PromotionProvider } from "@/contexts/PromotionContext";
import { OrderProvider } from "@/contexts/OrderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TuTiPet`s Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ProductTypeProvider>
            <ProductProvider>
              <CartContextProvider>
                <PromotionProvider>
                  <OrderProvider>
                    <LocationProvider>{children}</LocationProvider>
                  </OrderProvider>
                </PromotionProvider>
              </CartContextProvider>
            </ProductProvider>
          </ProductTypeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
